### ISSUE TITLE
Uncollapse sometimes stops working

### ISSUE THREAD

**Issue by robinedman** [guardian/scribe-plugin-noting#111]
![collapse-issue](https://cloud.githubusercontent.com/assets/1936213/6598991/03e0cc88-c7ff-11e4-809e-cbe1421a390d.gif)

**Steps to reproduce:**

1. Create a flag or correct.
2. Note it out.
3. Collapse the note.
4. Try to uncollapse the note by clicking it.
Result: Nothing happens.

**Comment by thekarel** [comment]
Can't reproduce in v0.4.5
