### ISSUE TITLE
`is-selection-within-note.js` and `is-selection-entirely-within-note`?

### ISSUE THREAD

**Issue by robinedman** [guardian/scribe-plugin-noting#121]
What's the difference between these? They look almost the same.

**Comment by cutandpastey** [comment]
if you have `<p>|This is <gu-note>some |content</gu-note></p>` `is-selection-within-note` returns `true` whereas `is-selection-entirely-within-note` returns `false`.

**Comment by robinedman** [comment]
Ah that makes sense!
