### ISSUE TITLE
Notes sometimes get created without a note id

### ISSUE THREAD

**Issue by robinedman** [guardian/scribe-plugin-noting#127]
https://composer-restorer.gutools.co.uk/content/553f8572e4b0b2b9b6f4df7f/versions

This article (not the newest version) includes this:

`<gu-note title="Vicky Frost 29/4/2015 at 15:36" data-note-edited-by="Vicky Frost" data-note-edited-date="2015-04-29T14:36:37.688Z" class="note">Courgette volumes</gu-note>`

![screen shot 2015-04-30 at 11 51 02](https://cloud.githubusercontent.com/assets/1936213/7411351/3509f350-ef2f-11e4-9861-a45d453bf9a5.png)

Note that it doesn't have a data-note-id.

Also note that it has no border at the start/end of it.

The lack of an id causes issues with merging, and probably other issues.

**Comment by na7hangood** [comment]
To replicate, create a not at the start of a para
https://composer.code.dev-gutools.co.uk/content/55507f76e4b0555c7183748c

**Comment by robinedman** [comment]
**Clarification to replication steps:**

1. Create a note at the start of a paragraph.
2. Create a note at the start of a subsequent paragraph.
