### ISSUE TITLE
Notes incorrectly concatenated, and include a visible 'space'

### ISSUE THREAD

**Issue by blishen** [guardian/scribe-plugin-noting#144]
#### Steps to reproduce:

1. In a Composer body text element type: "Word1 Word2"
2. Select "Word2" and note it.
3. Select "Word1" and note it.

#### Actual Result

The two notes are concatenated into a single note, the single note contains an un-noted space.
![image](https://cloud.githubusercontent.com/assets/479167/12233887/cfce32d8-b861-11e5-8102-259e0f08ab44.png)
#### Desired Result

There should be two discrete notes created with a visible un-noted space between them.

**Comment by thekarel** [comment]
Fixed in #146
