### ISSUE TITLE
Unnotes note and another note

### ISSUE THREAD

**Issue by robinedman** [guardian/scribe-plugin-noting#45]
![jprefactor2-unnote-bug](https://cloud.githubusercontent.com/assets/1936213/5435456/bbf285fa-8452-11e4-8a94-46de722ccbdb.gif)

**Steps to reproduce:**
1. Select a paragraph.
2. Unnote a word in the paragraph. There will now be two notes with an unnoted word in between.
3. Click somewhere within the first note.
4. Press the noting key.

Result: Both notes are unnoted, instead of just the first one.

**Appears to have been introduced by:** https://github.com/guardian/scribe-plugin-noting/pull/40

**Comment by cutandpastey** [comment]
Fixed with https://github.com/guardian/scribe-plugin-noting/pull/58
