### ISSUE TITLE
When stepping out of note a line of text is inserted

### ISSUE THREAD

**Issue by robinedman** [guardian/scribe-plugin-noting#46]
![jprefactor2-move-bug](https://cloud.githubusercontent.com/assets/1936213/5435709/d62fb700-8455-11e4-9724-3977d9b7e62d.gif)

**Steps: (only "works" about half the time)**

1. Create an empty note.
2. Write something.
3. Press right on your keyboard to step out of the note.

Result: A line of text is added to the end of the paragraph.

(Tried in this article on release: https://composer.release.dev-gutools.co.uk/content/548ecc1ae4b0f58829601ce5)

**May have been introduced by:** https://github.com/guardian/scribe-plugin-noting/pull/40

**Comment by cutandpastey** [comment]
Can't reproduce this one so im going to shut this issue down.
