### ISSUE TITLE
Noting three paragraps, unnoting part of the middle one causes browser to hang

### ISSUE THREAD

**Issue by robinedman** [guardian/scribe-plugin-noting#47]
**Steps to reproduce:**
1. Select three paragraphs.
2. Press the noting key.
3. Select a few words in the middle paragraph. There will now be two notes with a few unnoted words in between.
4. Place the caret somewhere inside the last note.
5. Try to unnote the note by pressing the noting key.

Result: Nothing happens and the browser hangs.

**Appears to have been introduced by:** https://github.com/guardian/scribe-plugin-noting/pull/40

**Comment by cutandpastey** [comment]
Can't reproduce this one.
