### ISSUE TITLE
Explicit type checking hides information

### ISSUE THREAD

**Issue by robinedman** [guardian/scribe-plugin-noting#52]
At the moment we have type checking like:
```
if (!isVFocus(focus)) {
    throw new Error('Only a valid VFocus element can be passed to findEntirenote');
}
```
(https://github.com/guardian/scribe-plugin-noting/blob/jp-refactor-note-toggle/src/utils/noting/find-entire-note.js#L23)

When [this is thrown](https://app.getsentry.com/digital-cms/composer/group/46800924/) we don't get any info about what `focus` actually is. In this sense it's harder to debug what actually happened than if we wouldn't have had it all.

Could we either:

1. Standardise on a type check function that will display relevant details like parameters in the error message?
2. Or simply rely on our unit tests instead of these checks?

**Comment by cutandpastey** [comment]
Is fixed in https://github.com/guardian/scribe-plugin-noting/pull/60, I'll close this when it's merged.

**Comment by rrees** [comment]
@robinedman I think I would lean towards option two as well and if you still have a type or validity check push it to boundaries of the code path

**Comment by cutandpastey** [comment]
Right now we have a handleError function which gives us a full print out a focus which causes error.  I think @theefer has a very good point here: https://github.com/guardian/scribe-plugin-noting/pull/60#discussion-diff-22654506 I'll migrate to this solution at a later date
