### ISSUE TITLE
Unnote part of note inserts text

### ISSUE THREAD

**Issue by robinedman** [guardian/scribe-plugin-noting#53]
**Present in #40**

![jprefactor2-unnote-part-inserts-text](https://cloud.githubusercontent.com/assets/1936213/5454887/5315477a-852e-11e4-86ea-4b99f861ac01.gif)

**Comment by cutandpastey** [comment]
This seems to be fixed somewhere within https://github.com/guardian/scribe-plugin-noting/pull/58 or https://github.com/guardian/scribe-plugin-noting/pull/59 see (on my local):

![noting-breaking-bug](https://cloud.githubusercontent.com/assets/1975139/5633398/b6ecb228-95ce-11e4-90e9-77fcc8f1788b.gif)

@robinedman @hmgibson23 can you check this when https://github.com/guardian/scribe-plugin-noting/pull/59 is merged?
