### ISSUE TITLE
The name isWithinNote is misleading

### ISSUE THREAD

**Issue by robinedman** [guardian/scribe-plugin-noting#54]
The name `isWithinNote` doesn't do what the name suggests.

**It returns true for:**
- All VNodes (that are not a VText node).
- All empty VText nodes.
- All VText nodes that has a note as an ancestor. 

This function is used when merging adjacent notes. The idea is that you call this function on a focus that you _already know_ is within a note, and then you `filter` forwards or backwards until you step out of what should be considered part of this note. 

Previously the function was called `stillWithinNote`, but maybe we can come up with a better name.

**Comment by cutandpastey** [comment]
Closing as https://github.com/guardian/scribe-plugin-noting/pull/84 fixed this.
