### ISSUE TITLE
Unnoting another note

### ISSUE THREAD

**Issue by robinedman** [guardian/scribe-plugin-noting#55]
This is an old one.

![unnoting-too-much-bug](https://cloud.githubusercontent.com/assets/1936213/5506871/19b01f22-8796-11e4-979d-2f0f612f7c2f.gif)

Both notes get unnoted since they still share the same id. If we make any change to the content, e.g. by typing a letter then `ensureNoteIntegrity` will sort that out for us and unnoting either note will then work as expected.
 
I probably introduced this bug when I fixed another one (make three paragraphs, unnote some text in the middle one, then unnote one of the paragraphs and everything would be unnoted). Previously we didn't rely on ids (rather on adjacenty as defined by `stillWithinNote`/`isWitinNote`), but sometimes that turned out to be problematic, so fixing might not be trivial.

One idea could be to use the "id strategy" when the note encompasses more than a paragraph and the "adjacency strategy" if not. But it might make sense to have a think about this. Maybe there's a better way.

**Comment by cutandpastey** [comment]
Should be fixed by https://github.com/guardian/scribe-plugin-noting/pull/58
