### ISSUE TITLE
Noting does not work after inserting an image

### ISSUE THREAD

**Issue by nealmadlani** [guardian/scribe-plugin-noting#75]
1. Create a new article
2. Create a few paragraphs and make some notes. Noting works fine
3. Add an image to the article inline
4. Try to note some text out

Actual: The noting button no longer works. 
Workaround: You can still use the shortcut keys to note stuff out.

![noting after images](https://cloud.githubusercontent.com/assets/2758960/5841284/a7059fac-a193-11e4-859e-80731f1cfc58.gif)

I get the following error in my console:

Uncaught Error: only a valid VFocus can be passed to findFirstNoteSegment, you passed: undefinedscribe-plugin-noting.js:10907 
t.exportsscribe-plugin-noting.js:11099 
t.exportsscribe-plugin-noting.js:9733 
t.exportsscribe-plugin-noting.js:10647 
(anonymous function)scribe-plugin-noting.js:10835 
(anonymous function)scribe-plugin-noting.js:10819 
n.mutatescribe-plugin-noting.js:10834 
(anonymous function)transaction-manager.js:29 
e.runscribe-plugin-noting.js:10829 
n.mutateScribescribe-plugin-noting.js:10627 
(anonymous function)scribe-plugin-noting.js:10647 
n.note.valuescribe-plugin-noting.js:10546 
(anonymous function)scribe-plugin-noting.js:7062 
(anonymous function)scribe-plugin-noting.js:7061 
i.triggerscribe-plugin-noting.js:10724 
n.executescribe-plugin-toolbar.js:22 
(anonymous function)

**Comment by cutandpastey** [comment]
@nealmadlani do you have any e2e tests for this in composer?
