### ISSUE TITLE
Adding a space at the start of a note, cancels the note

### ISSUE THREAD

**Issue by nealmadlani** [guardian/scribe-plugin-noting#80]
1. Write some text
2. Click the noting button to start a new note
3. Hit spacebar
Expected: A space should exist as the first character in the note
Actual: The note is cancelled

**Comment by cutandpastey** [comment]
Looking into this now.

**Comment by cutandpastey** [comment]
I'm copying in @robinedman. The problem occurs during `ensureNoteIntegrity`.  `resetNoteBarriers` causes something to happen where `preventErroneousBrTags` runs and deletes a note that contains a zero-width space and an actual space.  Ive gone through the code line by line and not much has changed so I assume this has been a bug for a while (hence I need @robinedman to look at this).

I can fix the issue by changing `resetNoteBarriers` but any change in here seems to make the caret move to the previous note.

Removing `preventErroneousBrTags` causes tests to fail.

**Comment by robinedman** [comment]
This is a side effect of a Scribe bug: https://github.com/guardian/scribe/issues/254

We should fix that Scribe bug instead of hacking around it in the noting plugin. That'll also allow us to remove the existing workaround for the bug (`preventErroneousBrTags`).

**Comment by cutandpastey** [comment]
:+1:

**Comment by robinedman** [comment]
Not happening anymore.
