### ISSUE TITLE
Zero width space added after noted out end of paragraph

### ISSUE THREAD

**Issue by rcrphillips** [guardian/scribe-plugin-noting#86]
Add a note to the end of a paragraph.

On the next line add a url to embed

Inspect the url  - you'll see that a zero width space html entity has been added to the start of the url, causing the embed to fail e.g. &#8203;https://soundcloud.com/badbadnotgood/badbadnotgood-ghostface-killah-ray-gun-feat-doom

@cutandpastey

**Comment by cutandpastey** [comment]
Related to https://github.com/guardian/scribe-plugin-noting/issues/85.
