### ISSUE TITLE
Toggle correct/flag via keyboard shortcut

### ISSUE THREAD

**Issue by robinedman** [guardian/scribe-plugin-noting#96]
It's currently only possible to toggle between flag and correct by using the mouse. It'd be nice to be able to use the keyboard.

@cutandpastey suggested binding the current click action to a key (not the same as the noting or flag key) and we agreed this would be the best for keeping the code clean and should also be usable enough (@alastairjardine: You agree?).

**Comment by alastairjardine** [comment]
@robinedman Had a wee chat with @cutandpastey and we thought that F6 and F7 would be good enough.

**Comment by cutandpastey** [comment]
This is completed in Composer
